In [1]:
import numpy as np
import pandas as pd

In [2]:
# Creamos un generador de números aleatorios utilizando la función default_rng() de NumPy.
rng = np.random.default_rng()

#Usamos para generar números enteros aleatorios entre 0 y 100, con un tamaño de 10.
a_values = rng.integers(low = 0, high = 100, size = 10) 

#Usamos para generar números enteros aleatorios entre 100 y 500, con un tamaño de 10.
b_values = rng.integers(low = 100, high = 500, size = 10)

#Creamos un DataFrame de pandas con dos columnas, 'A' y 'B', utilizando los valores generados anteriormente.
data = pd.DataFrame({'A': a_values, 'B': b_values})
data

    A    B
0  66  139
1  87  394
2  32  265
3   4  392
4  26  216
5  20  307
6   9  270
7  21  426
8  35  472
9  33  176

In [ ]:
# Ahora con cut podemos categorizar los valores de la columna 'A' en diferentes rangos, asignando etiquetas a cada rango.

data['A_cat'] = pd.cut(data.A, bins = [0, 20, 40, 60, 80, 100], labels = ['Muy poco', 'Poco', 'Normal', 'Mucho', 'Demasiado'])
data

    A    B      A_cat
0  66  139      Mucho
1  87  394  Demasiado
2  32  265       Poco
3   4  392   Muy poco
4  26  216       Poco
5  20  307   Muy poco
6   9  270   Muy poco
7  21  426       Poco
8  35  472       Poco
9  33  176       Poco

In [ ]:
# Aqui creamos un diccionario para MAPEAR las categorias

A_cat_mapper = {'Poco': 'Insuficiente',
                'Muy poco' : 'Insuficiente',
                'Normal' : 'Suficiente',
                'Mucho' : 'Suficiente',
                'Demasiado' : 'Suficiente'}

In [7]:
data['A_cat_mapper_insuf'] = data.A_cat.map(A_cat_mapper)
data

    A    B      A_cat A_cat_mapper_insuf
0  66  139      Mucho         Suficiente
1  87  394  Demasiado         Suficiente
2  32  265       Poco       Insuficiente
3   4  392   Muy poco       Insuficiente
4  26  216       Poco       Insuficiente
5  20  307   Muy poco       Insuficiente
6   9  270   Muy poco       Insuficiente
7  21  426       Poco       Insuficiente
8  35  472       Poco       Insuficiente
9  33  176       Poco       Insuficiente

In [9]:
# Usamos dummies para convertir las categorias de la columna 'A_cat' en variables dummy (variables binarias) para cada categoria.

A_categories_1_dummies = pd.get_dummies(data.A_cat, drop_first = True, prefix = 'A_cat1', dtype = int)
A_categories_1_dummies

   A_cat1_Poco  A_cat1_Normal  A_cat1_Mucho  A_cat1_Demasiado
0            0              0             1                 0
1            0              0             0                 1
2            1              0             0                 0
3            0              0             0                 0
4            1              0             0                 0
5            0              0             0                 0
6            0              0             0                 0
7            1              0             0                 0
8            1              0             0                 0
9            1              0             0                 0

In [10]:
A_categories_2_dummies = pd.get_dummies(data.A_cat_mapper_insuf, drop_first = True, prefix = 'A_cat2', dtype = int)
A_categories_2_dummies

   A_cat2_Suficiente
0                  1
1                  1
2                  0
3                  0
4                  0
5                  0
6                  0
7                  0
8                  0
9                  0

In [12]:
pd.Timestamp('2020-05-08')

Timestamp('2020-05-08 00:00:00')

In [13]:
pd.Period('2012-05', freq = 'D')

Period('2012-05-01', 'D')