In [1]:
import numpy as np
import seaborn as sns
import pandas as pd

In [2]:
df = sns.load_dataset('penguins')
print(df.shape)
df.sample(5)

(344, 7)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
126,Adelie,Torgersen,38.8,17.6,191.0,3275.0,Female
146,Adelie,Dream,39.2,18.6,190.0,4250.0,Male
192,Chinstrap,Dream,49.0,19.5,210.0,3950.0,Male
189,Chinstrap,Dream,52.0,20.7,210.0,4800.0,Male
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female

In [3]:
df.pivot_table('body_mass_g', index = 'species', columns = 'sex')

sex             Female         Male
species
Adelie     3368.835616  4043.493151
Chinstrap  3527.205882  3938.970588
Gentoo     4679.741379  5484.836066

In [4]:
df['flipper_length_mm'].describe()[['min', 'mean', 'max']]

min     172.000000
mean    200.915205
max     231.000000
Name: flipper_length_mm, dtype: float64

In [7]:
flipper_cat = pd.cut(df.flipper_length_mm, [172, 200, 231])
df.pivot_table('body_mass_g',['species', flipper_cat,],'sex')

C:\Users\LEON SUAREZ\AppData\Local\Temp\ipykernel_11936\2514864029.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table('body_mass_g',['species', flipper_cat,],'sex')

sex                               Female         Male
species   flipper_length_mm
Adelie    (172, 200]         3369.366197  4029.477612
          (200, 231]         3550.000000  4200.000000
Chinstrap (172, 200]         3531.060606  3704.411765
          (200, 231]         3400.000000  4173.529412
Gentoo    (200, 231]         4679.741379  5484.836066

In [9]:
bill_categories = pd.qcut(df.bill_length_mm, 3, labels = ['pequeño', 'mediano', 'grande'])
df.pivot_table('body_mass_g', ['species', flipper_cat],[bill_categories, 'sex'], fill_value = "No existe")

C:\Users\LEON SUAREZ\AppData\Local\Temp\ipykernel_11936\4010663218.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table('body_mass_g', ['species', flipper_cat],[bill_categories, 'sex'], fill_value = "No existe")

bill_length_mm                   pequeño                 mediano               \
sex                               Female       Male       Female         Male
species   flipper_length_mm
Adelie    (172, 200]         3364.338235     3980.0  3483.333333  4102.777778
          (200, 231]              3550.0     4300.0    No existe       4180.0
Chinstrap (172, 200]           No existe  No existe  3513.095238    No existe
          (200, 231]           No existe  No existe       3400.0    No existe
Gentoo    (200, 231]           No existe  No existe  4633.333333       5220.0

bill_length_mm                  grande
sex                             Female         Male
species   flipper_length_mm
Adelie    (172, 200]         No existe    No existe
          (200, 231]         No existe    No existe
Chinstrap (172, 200]            3562.5  3704.411765
          (200, 231]         No existe  4173.529412
Gentoo    (200, 231]         4801.5625  5536.764706