In [1]:
import pandas as pd

df1 = pd.DataFrame({
    "A": ["ΑΘ", "A1", "A2", "A3"], 
    "B": ["80", "81", "82", "83"], 
    "C": ["CO", "C1", "C2", "C3"], 
    "D": ["DO", "D1", "D2", "D3"], 
 }, index=[0,1,2,3])

df2 = pd.DataFrame({
    "A": ["A4", "AS", "A6", "A7"],
    "B": ["BA", "B", "86","87"], 
    "C": ["CA", "CS", "06", "C7"], 
    "D": ["04","05", "06", "07"], 
 }, index=[4,5,6,7])

df3 = pd.DataFrame({
    "A": ["AB", "AS", "A10", "A11"], 
    "B": ["88","89","810", "811"],
    "C": ["CB", "C", "C10", "C11"], 
    "D": ["08","09", "010", "D11"], 
 }, index=[8,9,10,11])

In [2]:
print(df1)

    A   B   C   D
0  ΑΘ  80  CO  DO
1  A1  81  C1  D1
2  A2  82  C2  D2
3  A3  83  C3  D3

In [3]:
print(df2)

    A   B   C   D
4  A4  BA  CA  04
5  AS   B  CS  05
6  A6  86  06  06
7  A7  87  C7  07

In [4]:
print(df3)

      A    B    C    D
8    AB   88   CB   08
9    AS   89    C   09
10  A10  810  C10  010
11  A11  811  C11  D11

In [5]:
resultado = pd.concat([df1,df2], axis = 1)
print(resultado)

     A    B    C    D    A    B    C    D
0   ΑΘ   80   CO   DO  NaN  NaN  NaN  NaN
1   A1   81   C1   D1  NaN  NaN  NaN  NaN
2   A2   82   C2   D2  NaN  NaN  NaN  NaN
3   A3   83   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   BA   CA   04
5  NaN  NaN  NaN  NaN   AS    B   CS   05
6  NaN  NaN  NaN  NaN   A6   86   06   06
7  NaN  NaN  NaN  NaN   A7   87   C7   07

In [6]:
frames = [df1, df2, df3]
result = pd.concat(frames)
result

      A    B    C    D
0    ΑΘ   80   CO   DO
1    A1   81   C1   D1
2    A2   82   C2   D2
3    A3   83   C3   D3
4    A4   BA   CA   04
5    AS    B   CS   05
6    A6   86   06   06
7    A7   87   C7   07
8    AB   88   CB   08
9    AS   89    C   09
10  A10  810  C10  010
11  A11  811  C11  D11

In [7]:
resultado = pd.concat([df1, df2], axis = 1, join = 'outer')
resultado

     A    B    C    D    A    B    C    D
0   ΑΘ   80   CO   DO  NaN  NaN  NaN  NaN
1   A1   81   C1   D1  NaN  NaN  NaN  NaN
2   A2   82   C2   D2  NaN  NaN  NaN  NaN
3   A3   83   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   BA   CA   04
5  NaN  NaN  NaN  NaN   AS    B   CS   05
6  NaN  NaN  NaN  NaN   A6   86   06   06
7  NaN  NaN  NaN  NaN   A7   87   C7   07

In [8]:
resultado = pd.concat([df1, df3], axis = 1, join = 'inner')
resultado

Empty DataFrame
Columns: [A, B, C, D, A, B, C, D]
Index: []